name: Prisma Migrate

on:
  push:
    branches: [main]
    paths:
      - "./prisma/**/*.*"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        run: npm i

  generate:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        run: npm i

      - run: rm -rf node_modules/.prisma

      - name: Generate Prisma Client
        run: npx prisma generate

  migrate:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        run: npm i

      - run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DB_URL: ${{ secrets.DB_URL }}
