name: test
on: push
    branches:
      - main

jobs:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npx prisma migrate deploy